JAVAC = javac
JAVA = java
SRC = FenetrePrincipale.java
CLASS = FenetrePrincipale.class
MAIN = FenetrePrincipale

all: $(CLASS)

$(CLASS): $(SRC)
	$(JAVAC) $(SRC)

run: $(CLASS)
	$(JAVA) $(MAIN)

clean:
	rm -f *.class
